name:                KTscheme1D
version:             0.1.0.0
github:              "xayon40-12/KTscheme"
license:             BSD3
author:              "Nathan Touroux"
maintainer:          "touroux.nathan@gmail.com"
copyright:           "2020 Nathan Touroux"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Development

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/xayon40-12/KTscheme#readme>

dependencies:
- base >= 4.7 && < 5
- array
- gloss

library:
  source-dirs: src

executables:
  KTscheme-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - KTscheme1D

tests:
  KTscheme-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - KTscheme1D
